#!/usr/bin/env bash
#Bash script that generates a MySQL dump and creates a compressed archive

mysqldump -uroot -p"$1" --all-databases > backup.sql

archive="$(date +'%d-%m-%Y').tar.gz"

tar -czf "$archive" backup.sql
