#!/usr/bin/env bash
#Bash script that accepts one argument

#Create a newuser
sudo useradd -m -s /bin/bash -g users "$1"
# Runs the 'whoami' command under the user passed as an argument
su "$1" -c "whoami"
